

server:
  port: 8101

#对应服务注册中心的配置内容，指定服务注册中心的位置(即eureka-server),为什么配的是http://localhost:8081/eureka/ 而不是http://localhost:8081/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/


#spring:
#  zipkin:
#    base-url: http://localhost:9411

spring:
  rabbitmq:
      host: localhost
      port: 15672


